### PR TITLE
feat: require api keys

### PR DESCRIPTION
**Pull request by sachyco**

### CODE REVIEW

**Review by christophwitzko — APPROVED** [review]
LGMT 🎉

**Comment by sachyco** [comment]
@christophwitzko Just added the ability to provide an api key in the providerConfig. How do you feel about the way I did this?

The client will add the key to the `Provider-API-Key` header and delete it from the request body.

**Comment by christophwitzko** [comment]
I like it! I wonder if users should still be able to configure the API key in the `Client` constructor 🤔  WDYT?

**Comment by sachyco** [comment]
> I like it! I wonder if users should still be able to configure the API key in the `Client` constructor 🤔 WDYT?

The provider key? Only problem there is that what if they use different provider configs for different requests with the same client? We'd have to keep track of keys for each provider.

**Comment by christophwitzko** [comment]
Good point 👌 Feel free to merge your PR.

**Pull request merged**
