### PR TITLE
openai library api compatibility

### PR DESCRIPTION
**Pull request by christophwitzko**

### CODE REVIEW

**Review by heikir — APPROVED** [review]
Looks great. Two high level comments:

1. Is there no way how to avoid bringing in `openai` and `axios` deps? I remember axios dep making the sdk unusable in some environments (I cannot remember which one exactly, but I have run into that issue in the past).
2. I like the idea that we introduce here, but I also see this moving away from the principle of having opinionated API design. I am happy to merge this now, but in general, I am not sure that's the path we want to take in the longer term.

Thoughts @Gregoor @christophwitzko ?

**Comment by christophwitzko** [comment]
One option would be to add them to the `peerDependencies`. That means users have to install axios and openai themselves. I will have to look into it if it works.

**Comment by Gregoor** [comment]
Great stuff, I'd disagree on both of Heiki's points, more specifically wrt 2) I think the point of this here is to make onboarding from OpenAI simple thus we have to throw all our opinions away, no?

Wrt 1) I'm also leaning towards keeping the dependency so that we don't have to re-implement/copy all the types and interfaces. The dependency is small and the environment is node so I don't think we have to stay so lean.

Two more ideas for this PR:
1. export everything from `openai`, overwriting with our own export what we want to overwrite
2. using TS's verify to make sure all our overwrites are still API compatible

Or put in code:

```diff
diff --git a/openai/index.ts b/openai/index.ts
index 0da32d9..a2be203 100644
--- a/openai/index.ts
+++ b/openai/index.ts
@@ -4,65 +4,7 @@ import * as originalOpenAI from "openai";
 
 import { Client } from "../client";
 
-export {
-  ChatCompletionRequestMessage,
-  ChatCompletionRequestMessageRoleEnum,
-  ChatCompletionResponseMessage,
-  ChatCompletionResponseMessageRoleEnum,
-  Configuration,
-  ConfigurationParameters,
-  CreateAnswerRequest,
-  CreateAnswerResponse,
-  CreateAnswerResponseSelectedDocumentsInner,
-  CreateChatCompletionRequest,
-  CreateChatCompletionResponse,
-  CreateChatCompletionResponseChoicesInner,
-  CreateClassificationRequest,
-  CreateClassificationResponse,
-  CreateClassificationResponseSelectedExamplesInner,
-  CreateCompletionRequest,
-  CreateCompletionResponse,
-  CreateCompletionResponseChoicesInner,
-  CreateCompletionResponseChoicesInnerLogprobs,
-  CreateCompletionResponseUsage,
-  CreateEditRequest,
-  CreateEditResponse,
-  CreateEmbeddingRequest,
-  CreateEmbeddingResponse,
-  CreateEmbeddingResponseDataInner,
-  CreateEmbeddingResponseUsage,
-  CreateFineTuneRequest,
-  CreateImageRequest,
-  CreateImageRequestResponseFormatEnum,
-  CreateImageRequestSizeEnum,
-  CreateModerationRequest,
-  CreateModerationResponse,
-  CreateModerationResponseResultsInner,
-  CreateModerationResponseResultsInnerCategories,
-  CreateModerationResponseResultsInnerCategoryScores,
-  CreateSearchRequest,
-  CreateSearchResponse,
-  CreateSearchResponseDataInner,
-  CreateTranscriptionResponse,
-  CreateTranslationResponse,
-  DeleteFileResponse,
-  DeleteModelResponse,
-  Engine,
-  FineTune,
-  FineTuneEvent,
-  ImagesResponse,
-  ImagesResponseDataInner,
-  ListEnginesResponse,
-  ListFilesResponse,
-  ListFineTuneEventsResponse,
-  ListFineTunesResponse,
-  ListModelsResponse,
-  Model,
-  OpenAIApiAxiosParamCreator,
-  OpenAIApiFactory,
-  OpenAIApiFp,
-  OpenAIFile,
-} from "openai";
+export * from "openai";
 
 interface CreateCompletionRequest
   extends originalOpenAI.CreateCompletionRequest {
diff --git a/openai/verify.ts b/openai/verify.ts
new file mode 100644
index 0000000..667069e
--- /dev/null
+++ b/openai/verify.ts
@@ -0,0 +1,7 @@
+import * as openAI from "openai";
+
+import * as commonBaseShim from ".";
+
+commonBaseShim satisfies typeof openAI;
+
+commonBaseShim.OpenAIApi;

```

**Comment by christophwitzko** [comment]
@Gregoor I really like the idea to verify the compatibility. (I already pushed the change on the branch)

1.) I kinda like the peerDependencies idea, as it only requires users that want to rely on openai to actually install the dependencies. However, this requires an extra step of installing the dependencies, and the `axios` version could easily mismatch (openai uses a much older version of axios), so I am still unsure how we can solve it in the best possible way.

2.) I agree here also with @Gregoor, we want users to easily adopt our SDK so we need to adapt to the already existing API design.

**Comment by heikir** [comment]
Good inputs from everyone!

1. I would favor the peerDependencies idea as well. As I said, I had an issue using openai npmjs package in the past since they rely on axios which is not supported in every environment (for example the edge https://github.com/axios/axios/issues/5523 and also Chrome plugins background env if I remember correctly). Would using peerDependencies solve the issue of using commonbase sdk working in those environments?
2. Let's go with the wrapper for the time being. I wonder how introducing the next api will affect that decision, but perhaps we can make the assumption that most people are using openai as a starting point.

**Comment by christophwitzko** [comment]
@heikir If you use "our" library, it will always work (whether axios/openai is a peerDependency or a regular dependency). Only if you use the `openai` shim, you would need to run it on an environment that is supported by axios.

**Comment by heikir** [comment]
As discussed on the call, let's merge :)

**Pull request merged**
